// designedbybruno — parchment warmth, cinnabar signature, navy structure, film grain.
export const T = {
  bg: '#F0EDE6',
  surface: '#F5F0E1',
  surfaceRaised: '#FBF8F0',
  ink: '#1A1A1A',
  inkSoft: '#3A362F',
  muted: '#8A8578',
  border: '#D6D0C4',
  navy: '#1B2D4F',
  navyDeep: '#14213D',
  orange: '#D4622B',
  orangeSoft: '#E8844A',
  gold: '#C9922A',
  red: '#C4391D',
  green: '#52B788',
  cream: '#F5F0E1',
  white: '#FAFAF7',
  display: "'Space Grotesk', 'Arial Black', sans-serif",
  body: "'Inter', system-ui, sans-serif",
  mono: "'JetBrains Mono', 'SF Mono', monospace",
  easeOut: [0.16, 1, 0.3, 1] as [number, number, number, number],
  spring: { type: 'spring', stiffness: 380, damping: 30 } as const,
};
